### ISSUE TITLE
e2e in Rust?

### ISSUE THREAD

**Issue by adsick** [leptos-rs/start#22]
not a pro in this regard, but maybe it is better to write e2e tests in pure Rust?

**Comment by gbj** [comment]
What makes you say so? It's not that I think it's wrong per se, it's just that Playwright is a very well-known testing tool with built-in support from cargo-leptos, and wasm-pack test is a bit hard to work with. (I've written some about using it in the Leptos book and we have some examples of testing using it in the repo.)

I'm open to a PR adding Rust tests as an alternative.

**Comment by adsick** [comment]
> What makes you say so?

The fact that I like all things Rust I guess.

> I'm open to a PR adding Rust tests as an alternative.

I'm not the one who can do that atm.
