### ISSUE TITLE
Attempting to `Executing a Server on a Remote Machine Without the Toolchain`

### ISSUE THREAD

**Issue by kruserr** [leptos-rs/start#26]
Attempting to follow the https://github.com/leptos-rs/start#executing-a-server-on-a-remote-machine-without-the-toolchain.

When building in release and then running the server, the HTML points to `/pkg/leptos_start_bg.wasm`, but the generated file is named `/pkg/leptos_start.wasm`.

console:
```log
GET http://localhost:3000/pkg/leptos_start_bg.wasm 404 (Not Found)
```

HTML:
```html
...
<head>
  ...
  <link rel="preload" href="/pkg/leptos_start_bg.wasm" as="fetch" type="application/wasm" crossorigin="">
  ...
</head>
...
```

ls at `target/server/release`:
```sh
$ ls pkg
leptos_start.css  leptos_start.js  leptos_start.wasm  snippets
```

Versions:
- rustc 1.72.0-nightly
- cargo-leptos-0.1.11
- leptos-rs/start d193e54b768d12b932f41ffa50299358a4121657

Steps to reproduce:
```sh
# Deps
rustup toolchain install nightly
rustup default nightly
rustup target add wasm32-unknown-unknown
cargo install --locked cargo-generate
npm install -g sass

# init leptos-rs/start
cargo install --locked cargo-leptos
cargo leptos new --git https://github.com/leptos-rs/start
cd ${PROJ_NAME}

# Build in release
cargo leptos build --release
cd target/server/release
cp -r ../../site/* .

# Set env vars
LEPTOS_OUTPUT_NAME="leptos_start"
LEPTOS_SITE_ROOT="site"
LEPTOS_SITE_PKG_DIR="pkg"
LEPTOS_SITE_ADDR="127.0.0.1:3000"
LEPTOS_RELOAD_PORT="3001"

# exec
./leptos_start
```

**Comment by kruserr** [comment]
May be related to: https://github.com/leptos-rs/cargo-leptos/issues/143

Attempted to build and run without setting `$LEPTOS_OUTPUT_NAME`, but HTML still wants to load with postfix `_bg`.

**Comment by gbj** [comment]
This is somewhat odd. I am not a shell expert by any means, but if I run:
```bash
cargo leptos build --release
cd target/server/release
cp -r ../../site/* .
LEPTOS_OUTPUT_NAME="leptos_start" ./leptos_start
```
it works correctly.

Is there some difference in behavior between how you were setting the environment variables and how including it in the `./leptos_start` command works? I genuinely don't know.

**Comment by kruserr** [comment]
Okey just tired `LEPTOS_OUTPUT_NAME="leptos_start" ./leptos_start` and that looks like it works.

Double checked the other commands, and they still don't work, even though the env vars are set correctly in the shell.

How are the env vars read?

**Comment by kruserr** [comment]
Ah yes I see, I forgot you have to `export` env vars when setting them in the shell like that.

```sh
export LEPTOS_OUTPUT_NAME="leptos_start"
export LEPTOS_SITE_ROOT="site"
export LEPTOS_SITE_PKG_DIR="pkg"
export LEPTOS_SITE_ADDR="127.0.0.1:3000"
export LEPTOS_RELOAD_PORT="3001"
```
