### ISSUE TITLE
problem realated to leptos actix template

### ISSUE THREAD

**Issue by dhrubrawat66** [leptos-rs/start#34]
i run cargo leptos watch on terminal i got this problem
![Screenshot 2023-09-08 181505](https://github.com/leptos-rs/start/assets/85351405/8359c44b-6c40-4a8e-bdd1-31a4bc705bb8)
how to solve this problem? please help me.

**Comment by gbj** [comment]
Do you mean the warning that says it might become a hard error in the future? There's no actual issue here, as far as I can tell. Your app should be working as expected and available at http://localhost:3000, or whatever address you chose if you changed that.
