### ISSUE TITLE
Lepts setip project fails due to build erros

### ISSUE THREAD

**Issue by NuLL3rr0r** [leptos-rs/start#35]
Just started testing out Leptos:
```
$ cargo install trunk cargo-leptos   

$cargo leptos new --git https://github.com/leptos-rs/star
```
And then I do:
```
$ cargo leptos watch
```
Or, even:
```
$ cargo leptos build --release
```

I get the attached filer errors
[build.log](https://github.com/leptos-rs/start/files/13059331/build.log)

**Comment by gbj** [comment]
The following appears 33 times in the attached log:
```
  = note: the `wasm32-unknown-unknown` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`
```
Have you [added the `wasm32-unknown-unknown` target](https://github.com/leptos-rs/start#installing-additional-tools)?

**Comment by NuLL3rr0r** [comment]
Thanks for pointing that out, I've never been so embarrassed for not carefully reading the logs 🙈 though according to rustup I already have it:

```
~/.cargo/bin/rustup target add wasm32-unknown-unknown
                                                       
info: component 'rust-std' for target 'wasm32-unknown-unknown' is up to date
```

I use stable, but the link you've mentioned states "By default, cargo-leptos uses nightly Rust, ..."., so I switched to nightly:

```
~/.cargo/bin/rustup default nightly
~/.cargo/bin/rustup update
```

And it's building fine, thank you very much! I'll close the issue since it seems (if I'm not mistaken) nightly is a requirement.
