### ISSUE TITLE
License a bit annoying for a template: consider CC0, instead?

### ISSUE THREAD

**Issue by karlmdavis** [leptos-rs/start#38]
Obviously, this is entirely up to you, but I do think imposing permanent license requirements, including attribution, on projects created from a template is a bit onerous.

I went from "oh neat, a template I can use to get started quickly" to "oh, it dropped a `LICENSE` file in there, I wonder what it chose for me... oh, I don't mind MIT but now I'm thinking about what license I want to use for this project, rather than what I wanted to build and that feels pretty derailing."

You might consider [CC0](https://creativecommons.org/publicdomain/zero/1.0/), instead. And just mention that in the readme and that folks are free to choose their own license for their project, instead of pre-creating a `LICENSE` file in the project for them.

Regardless, thanks so much for such a helpful starter template!

**Comment by gbj** [comment]
Thanks for pointing this out -- this was not something that any thought has been put into. I've switched it to the Unlicense and will add a note to the README.
