### ISSUE TITLE
wasm-bindgen 0.2.91 version don't work

### ISSUE THREAD

**Issue by indierusty** [leptos-rs/start#46]
error on compiling:

`       Front compiling WASM
Error: at `/home/priyanshu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.2.17/src/compile/front.rs:47:30`

Caused by:
    0: at `/home/priyanshu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.2.17/src/compile/front.rs:122:10`
    1:

       it looks like the Rust project used to create this wasm file was linked against
       version of wasm-bindgen that uses a different bindgen format than this binary:

         rust wasm file schema version: 0.2.91
            this binary schema version: 0.2.92`

But wasm-bingen 0.2.92 works fine.

**Comment by gbj** [comment]
Thanks. We just need to update the templates whenever it is updated in cargo-leptos and I forgot. Should be closed by  11f60c8c233d17bcb1e4b62bf9b1f5c89208f841
